language: node_js
node_js:
- '10'
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn
- yarn --cwd docs/
script:
- yarn test
before_deploy:
- yarn --cwd docs/ run build
- sed -i '/_site/d' ./.gitignore
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/_site/
  verbose: true
  github_token: $GITHUB_SANDBOX_TOKEN
  on:
    branch: master
env:
  matrix:
    # $GITHUB_SANDBOX_TOKEN for cfpb/design-system (using the CFPBot GH account)
    # is set at https://travis-ci.org/github/cfpb-sandbox/design-system/settings
